version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_c
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend_c
    restart: always
    stdin_open: true
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx_c
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
